config/routes.rb
Rails.application.routes.draw do
  root 'article#list'

  get 'article/new' => 'article#new', as: :new_article
  get 'articles/:id/edit' => 'article#edit', as: :edit_article
  post 'articles' => 'article#create', as: :articles
  post 'article/:id/like' => 'article#like', as: :like_article

  get 'articles/:id' => 'article#detail', as: :article

  patch 'articles/:id' => 'article#update'

  delete 'article/:id' => 'article#delete', as: :delete_article

end

app/models/article.rb
class Article < ActiveRecord::Base

  validates :title, presence: true
  validates :name, presence: true
  validates :photo, presence: true
  validates :url, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/article_controller.rb
class ArticleController < ApplicationController
  def list
    @articles = Article.all.order("view_count desc")
  end

  def detail
    @article = Article.find params[:id]
  end

  def new
    @article = Article.new
  end

  def create
    # @article = Article.create(article_params)

    # .... same as
    @article = Article.new(article_params)
    if @article.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @article = Article.find params[:id]
  end

  def delete
    @article = Article.find params[:id]
    @article.destroy
    redirect_to root_path

  end

  def article_params
   params.require(:article).permit(:title, :name, :created_at, :photo, :id)
 end

 def like
     @article = Article.find params[:id]
     @article.update view_count: (@article.view_count + 1)
     redirect_to root_path
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/views/article/detail.html.erb
<div class= "container">
  <%= link_to 'Edit', edit_article_path %>
  <h1><%= @article.name %></h1>
</div>

app/views/article/edit.html.erb
<div class="container">
  <h1>Edit</h1>


  <%= simple_form_for @article do |f| %>
  <%= f.input :photo %>
  <%= f.input :title %>
  <%= f.input :name %>
  <%= f.input :url %>
  <%= f.button :submit %> or <%= link_to 'Delete', "delete_article_path", method: :delete, data: {confirm: "Are you sure?"} %>

<% end %>
</div>

app/views/article/list.html.erb
<div class="container">
<h1>Buildit</h1>
<hr>

<% @articles.each do |article| %>

  <div class= "content">




    <%= image_tag(article.photo) %>
  <h3 >
    <%= link_to article.title, article.url %>
</h3>
    <small>Published <%= distance_of_time_in_words_to_now article.created_at %> ago. </small>

    <%= link_to like_article_path(id: article.id), method: :post, class: 'btn btn-default' do %>
    <i class ="glyphicon glyphicon-thumbs-up"></i>
    <%= pluralize article.view_count, 'view' %>
    <% end %>




  <a><%= link_to article.name, article %> </a>
  </div>
<% end %>
</div>
</div>

app/views/article/new.html.erb
<div class="container">

  <h1>New</h1>


  <%= simple_form_for @article do |f| %>
  <%= f.input :photo %>
  <%= f.input :title %>
  <%= f.input :name %>
  <%= f.input :url %>
  <%= f.button :submit %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Buildit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav>
 <ul class="nav nav-tabs">

   <li role="presentation" class="active"><%= link_to 'Buildit', root_path %></li>
   <li role="presentation"><a href="#"><%=  'hot' %></a></li>
   <li role="presentation"><%= link_to 'New', new_article_path %></li>
   <li role="presentation"><a href="#"><%=  'rising' %></a></li>
   <li role="presentation"><a href="#"><%=  'controversial' %></a></li>
   <li role="presentation"><a href="#"><%=  'top' %></a></li>
   <li role="presentation"><a href="#"><%=  'gilded' %></a></li>
   <li role="presentation"><a href="#"><%=  'wiki' %></a></li>
   <li role="presentation"><a href="#"><%=  'promoted' %></a> </a></li>



 </ul>
</nav>



<div id="wrapper">

<%= yield %>

</div>
<br>
<br>
<hr>
<footer class="container">
  <p> Copyright © 2015 Ola Siyanbola. All Rights Reserved</p>
  </footer>

</body>
</html>